name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build Windows AMD64
        run: |
          GOOS=windows GOARCH=amd64 go build -o mpt-windows.exe .
      
      - name: Build Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o mpt-linux .
      
      - name: Build macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o mpt-macos .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            mpt-windows.exe
            mpt-linux
            mpt-macos
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mpt-windows.exe
            mpt-linux
            mpt-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

